name: CrownSMP
version: ${version}
main: me.baljeetpabla.crownsmp.CrownSMP
api-version: '1.21.11'
author: BaljeetPabla13
website: https://github.com/baljeetpabla13-cmyk/crownsmps
description: A player-controlled raid boss Crown SMP plugin.
commands:
  crown:
    description: Manage the Crown and Crown SMP systems.
    usage: /crown <set|give|darkset|darkgive|remove|darkremove|info|reload|help>
    permission: crownsmp.admin
permissions:
  crownsmp.admin:
    description: Allows administration of CrownSMP.
    default: op
